/**
 * Default ignore patterns layered on top of any .gitignore found at the root.
 * These catch common noise even when a project has a minimal or missing .gitignore.
 */
export const DEFAULT_IGNORES: readonly string[] = [
  // VCS
  ".git/",
  ".svn/",
  ".hg/",

  // Dependencies
  "node_modules/",
  "bower_components/",
  "vendor/",
  ".pnpm-store/",
  ".yarn/",

  // Lockfiles / package manager noise (content is huge and low-signal for LLMs)
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lockb",
  "Cargo.lock",
  "poetry.lock",
  "Pipfile.lock",
  "composer.lock",
  "Gemfile.lock",

  // Build / output
  "dist/",
  "build/",
  "out/",
  "target/",
  "coverage/",
  ".next/",
  ".nuxt/",
  ".svelte-kit/",
  ".turbo/",
  ".cache/",
  "*.tsbuildinfo",
  "*.map",

  // Python / JVM / etc.
  "__pycache__/",
  "*.pyc",
  ".venv/",
  "venv/",
  "*.egg-info/",
  ".tox/",
  ".mypy_cache/",
  ".pytest_cache/",
  "*.class",
  "*.jar",
  "*.war",

  // Binaries & archives
  "*.exe",
  "*.dll",
  "*.so",
  "*.dylib",
  "*.o",
  "*.a",
  "*.bin",
  "*.wasm",
  "*.zip",
  "*.tar",
  "*.tar.gz",
  "*.tgz",
  "*.rar",
  "*.7z",
  "*.gz",
  "*.bz2",

  // Large / binary media
  "*.png",
  "*.jpg",
  "*.jpeg",
  "*.gif",
  "*.webp",
  "*.ico",
  "*.svg",
  "*.bmp",
  "*.mp3",
  "*.mp4",
  "*.wav",
  "*.webm",
  "*.mov",
  "*.avi",
  "*.pdf",
  "*.psd",
  "*.ai",
  "*.ttf",
  "*.otf",
  "*.woff",
  "*.woff2",
  "*.eot",

  // Env / secrets (never pack by default)
  ".env",
  ".env.*",
  "!.env.example",
  "*.pem",
  "*.key",
  "id_rsa",
  "id_rsa.pub",
  "credentials.json",
  "service-account*.json",

  // IDE / OS
  ".idea/",
  ".vscode/",
  "*.swp",
  "*.swo",
  ".DS_Store",
  "Thumbs.db",

  // Logs
  "*.log",
  "npm-debug.log*",
  "yarn-debug.log*",
  "yarn-error.log*",
];

/** Patterns that look like text source even if extension is uncommon. */
export const TEXT_EXTENSIONS = new Set([
  ".ts",
  ".tsx",
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".json",
  ".md",
  ".mdx",
  ".txt",
  ".yml",
  ".yaml",
  ".toml",
  ".ini",
  ".cfg",
  ".conf",
  ".env.example",
  ".css",
  ".scss",
  ".sass",
  ".less",
  ".html",
  ".htm",
  ".xml",
  ".svg", // noted: default ignore still skips *.svg as media; include can override
  ".py",
  ".rb",
  ".go",
  ".rs",
  ".java",
  ".kt",
  ".kts",
  ".c",
  ".h",
  ".cpp",
  ".hpp",
  ".cc",
  ".cs",
  ".php",
  ".sh",
  ".bash",
  ".zsh",
  ".fish",
  ".ps1",
  ".sql",
  ".graphql",
  ".gql",
  ".proto",
  ".r",
  ".R",
  ".swift",
  ".m",
  ".mm",
  ".vue",
  ".svelte",
  ".astro",
  ".dockerfile",
  ".gitignore",
  ".gitattributes",
  ".editorconfig",
  ".eslintrc",
  ".prettierrc",
  ".npmrc",
  ".nvmrc",
]);

export const TEXT_BASENAMES = new Set([
  "Dockerfile",
  "Makefile",
  "Rakefile",
  "Gemfile",
  "Procfile",
  "LICENSE",
  "LICENCE",
  "CHANGELOG",
  "CONTRIBUTING",
  "README",
  "Cargo.toml",
  "Cargo.lock",
  "go.mod",
  "go.sum",
  "pyproject.toml",
  "setup.py",
  "requirements.txt",
  "CMakeLists.txt",
]);
